apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-exposed
  namespace: flux-system
spec:
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 9292
      protocol: TCP
      targetPort: 9292
